# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fast_flights/pb/flights.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'fast_flights/pb/flights.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x66\x61st_flights/pb/flights.proto\"\x1a\n\x07\x41irport\x12\x0f\n\x07\x61irport\x18\x02 \x01(\t\"\x90\x01\n\nFlightData\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x1e\n\x0c\x66rom_airport\x18\r \x01(\x0b\x32\x08.Airport\x12\x1c\n\nto_airport\x18\x0e \x01(\x0b\x32\x08.Airport\x12\x16\n\tmax_stops\x18\x05 \x01(\x05H\x00\x88\x01\x01\x12\x10\n\x08\x61irlines\x18\x06 \x03(\tB\x0c\n\n_max_stops\"k\n\x04Info\x12\x19\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x0b.FlightData\x12\x13\n\x04seat\x18\t \x01(\x0e\x32\x05.Seat\x12\x1e\n\npassengers\x18\x08 \x03(\x0e\x32\n.Passenger\x12\x13\n\x04trip\x18\x13 \x01(\x0e\x32\x05.Trip\"(\n\x05Price\x12\r\n\x05price\x18\x01 \x01(\x05\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\":\n\x10ItinerarySummary\x12\x0f\n\x07\x66lights\x18\x02 \x01(\t\x12\x15\n\x05price\x18\x03 \x01(\x0b\x32\x06.Price\"N\n\x0eSortPreference\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x05\x12\x1c\n\tsort_type\x18\x04 \x01(\x0e\x32\t.SortType\x12\x0e\n\x06\x66ield5\x18\x05 \x01(\x05\">\n\x07TfuData\x12#\n\npreference\x18\x02 \x01(\x0b\x32\x0f.SortPreference\x12\x0e\n\x06\x66ield4\x18\x04 \x01(\x0c*S\n\x04Seat\x12\x10\n\x0cUNKNOWN_SEAT\x10\x00\x12\x0b\n\x07\x45\x43ONOMY\x10\x01\x12\x13\n\x0fPREMIUM_ECONOMY\x10\x02\x12\x0c\n\x08\x42USINESS\x10\x03\x12\t\n\x05\x46IRST\x10\x04*E\n\x04Trip\x12\x10\n\x0cUNKNOWN_TRIP\x10\x00\x12\x0e\n\nROUND_TRIP\x10\x01\x12\x0b\n\x07ONE_WAY\x10\x02\x12\x0e\n\nMULTI_CITY\x10\x03*_\n\tPassenger\x12\x15\n\x11UNKNOWN_PASSENGER\x10\x00\x12\t\n\x05\x41\x44ULT\x10\x01\x12\t\n\x05\x43HILD\x10\x02\x12\x12\n\x0eINFANT_IN_SEAT\x10\x03\x12\x11\n\rINFANT_ON_LAP\x10\x04*4\n\x08SortType\x12\x10\n\x0cUNKNOWN_SORT\x10\x00\x12\x08\n\x04\x42\x45ST\x10\x01\x12\x0c\n\x08\x43HEAPEST\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fast_flights.pb.flights_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEAT']._serialized_start=563
  _globals['_SEAT']._serialized_end=646
  _globals['_TRIP']._serialized_start=648
  _globals['_TRIP']._serialized_end=717
  _globals['_PASSENGER']._serialized_start=719
  _globals['_PASSENGER']._serialized_end=814
  _globals['_SORTTYPE']._serialized_start=816
  _globals['_SORTTYPE']._serialized_end=868
  _globals['_AIRPORT']._serialized_start=33
  _globals['_AIRPORT']._serialized_end=59
  _globals['_FLIGHTDATA']._serialized_start=62
  _globals['_FLIGHTDATA']._serialized_end=206
  _globals['_INFO']._serialized_start=208
  _globals['_INFO']._serialized_end=315
  _globals['_PRICE']._serialized_start=317
  _globals['_PRICE']._serialized_end=357
  _globals['_ITINERARYSUMMARY']._serialized_start=359
  _globals['_ITINERARYSUMMARY']._serialized_end=417
  _globals['_SORTPREFERENCE']._serialized_start=419
  _globals['_SORTPREFERENCE']._serialized_end=497
  _globals['_TFUDATA']._serialized_start=499
  _globals['_TFUDATA']._serialized_end=561
# @@protoc_insertion_point(module_scope)
